version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: laravel_testing
          - MYSQL_ROOT_PASSWORD: password
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:yxzsYHn4oyivCjHhH4wq0+37CykF6WhOCOhgnqOE4B4=
      - DB_CONNECTION: mysql
      - DB_HOST: 127.0.0.1
      - DB_DATABASE: laravel_testing
      - DB_USERNAME: root
      - DB_PASSWORD: password

    working_directory: ~/TennisApp
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./server/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./server
      - save_cache:
          paths:
            - .server/vendor
          key: v1-dependencies-{{ checksum "./server/composer.json" }}
      - run:
          name: Run Test
          command: |
            php ./server/artisan --env=testing
            php ./server/artisan migrate
            php ./server/vendor/bin/phpunit --configuration=./server/phpunit.xml