version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - DB_CONNECTION: mysql
      - DB_DATABASE: laravel_testing
      - DB_USERNAME: root
    working_directory: ~/server
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "server/composer.json" }}
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit